name: WIP Publish to PyPi
on:
  workflow_call:

#Needs dist setup beforehand
jobs:
  publish-to-pypi:
    uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}