name: WIP Release
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: gordon/automated-release-workflow

jobs:
  test:
    uses: ./.github/workflows/tester.yaml

  create-tagged-release:
    needs: test
    uses: ./.github/workflows/createTaggedRelease.yml

  update-docs:
    needs: create-tagged-release
    uses: ./.github/workflows/updateDocs.yaml

  publish-to-pypi:
    needs: create-tagged-release
    uses: ./.github/workflows/publishToPyPi.yml