name: Release
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      one:
        uses: actions/checkout@v3
      two:
        uses: ./.github/workflows/test.yaml@gordon/automated-release-workflow