name: WIP Release
on:
  workflow_dispatch:
  push:
    branches: gordon/automated-release-workflow

jobs:
  test:
    uses: ./.github/workflows/tester.yaml
  create-tagged-release:
    needs: test
    uses: ./.github/workflows/createTaggedRelease.yml
#  publish-to-pypi:
#    needs:
#    uses: ./.github/workflows/publishToPyPi.yml