name: Test and Tag Release
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Enter tag version number for release below. Don't forget the v! Example: v2.23.9"
        type: string
        required: true
  push:
    branches: gordon/automated-release-workflow

jobs: 
  test:
    uses: ./.github/workflows/tester.yaml

  create-tagged-release:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: ${{ github.event.inputs.custom_tag }}

  generate-and-update-docs:
    needs: create-tagged-release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Generate docs and switch to docs branch
        run: |
          poetry run pdoc ./phdi -o ./docs/${{ github.event.inputs.custom_tag }}
          git checkout docs --

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit-message: Automated update of API docs for ${{ github.event.inputs.custom_tag }} release.



