name: Release
on:
  workflow_dispatch:
  push:
    branches: gordon/automated-release-workflow

jobs:
  unit-test-phdi-building-blocks-lib:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/test.yaml