name: Release
on:
  workflow_dispatch:

jobs:
  test:
    steps:
      checkout:
        uses: actions/checkout@v3
      run-test:
        uses: ./.github/workflows/test.yaml@gordon/automated-release-workflow