name: Release Me!
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Argh
        uses: actions/checkout@v3
      - name: Argh2
        uses: ./.github/workflows/test.yaml@gordon/automated-release-workflow