name: Release
on:
  workflow_dispatch:
  push:
    branches: gordon/automated-release-workflow

jobs:
  unit-test-phdi-building-blocks-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Whatever
        uses: ./.github/workflows/test.yaml@gordon/automated-release-workflow